version: "3.3"
services:
  redis:
    image: nginx:alpine
    ports:
     - 80:80
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure